export const departments = [
  {
    'college': '文學院',
    'code': '1010',
    'name': '中國文學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/10.pdf',
  },
  {
    'college': '文學院',
    'code': '1020',
    'name': '外國語文學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/11.pdf',
  },
  {
    'college': '文學院',
    'code': '1030',
    'name': '歷史學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/12.pdf',
  },
  {
    'college': '文學院',
    'code': '1040',
    'name': '哲學系碩士班甲組(主修東方哲學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/13.pdf',
  },
  {
    'college': '文學院',
    'code': '1050',
    'name': '哲學系碩士班乙組(主修西方哲學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/14.pdf',
  },
  {
    'college': '文學院',
    'code': '1060',
    'name': '人類學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/15.pdf',
  },
  {
    'college': '文學院',
    'code': '1070',
    'name': '圖書資訊學系碩士班甲組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/16.pdf',
  },
  {
    'college': '文學院',
    'code': '1080',
    'name': '圖書資訊學系碩士班乙組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/17.pdf',
  },
  {
    'college': '文學院',
    'code': '1090',
    'name': '圖書資訊學系碩士班丙組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/18.pdf',
  },
  {
    'college': '文學院',
    'code': '1100',
    'name': '圖書資訊學系碩士班丁組(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/19.pdf',
  },
  {
    'college': '文學院',
    'code': '1110',
    'name': '日本語文學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/20.pdf',
  },
  {
    'college': '文學院',
    'code': '1120',
    'name': '戲劇學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/21.pdf',
  },
  {
    'college': '文學院',
    'code': '1130',
    'name': '藝術史研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/22.pdf',
  },
  {
    'college': '文學院',
    'code': '1140',
    'name': '藝術史研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/23.pdf',
  },
  {
    'college': '文學院',
    'code': '1150',
    'name': '語言學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/24.pdf',
  },
  {
    'college': '文學院',
    'code': '1160',
    'name': '語言學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/25.pdf',
  },
  {
    'college': '文學院',
    'code': '1170',
    'name': '音樂學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/26.pdf',
  },
  {
    'college': '文學院',
    'code': '1180',
    'name': '音樂學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/27.pdf',
  },
  {
    'college': '文學院',
    'code': '1190',
    'name': '臺灣文學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/28.pdf',
  },
  {
    'college': '文學院',
    'code': '1200',
    'name': '華語教學碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/29.pdf',
  },
  {
    'college': '理學院',
    'code': '2010',
    'name': '數學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/30.pdf',
  },
  {
    'college': '理學院',
    'code': '2020',
    'name': '數學系碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/31.pdf',
  },
  {
    'college': '理學院',
    'code': '2030',
    'name': '物理學系碩士班(可選擇志願)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/32.pdf',
  },
  {
    'college': '理學院',
    'code': '2040',
    'name': '物理學系碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/33.pdf',
  },
  {
    'college': '理學院',
    'code': '2050',
    'name': '化學系碩士班化學組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/34.pdf',
  },
  {
    'college': '理學院',
    'code': '2060',
    'name': '化學系碩士班化學生物學組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/35.pdf',
  },
  {
    'college': '理學院',
    'code': '2070',
    'name': '地質科學系碩士班(可選擇志願)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/36.pdf',
  },
  {
    'college': '理學院',
    'code': '2080',
    'name': '心理學系碩士班一般心理學組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/37.pdf',
  },
  {
    'college': '理學院',
    'code': '2090',
    'name': '心理學系碩士班一般心理學組(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/38.pdf',
  },
  {
    'college': '理學院',
    'code': '2100',
    'name': '心理學系碩士班臨床心理學組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/39.pdf',
  },
  {
    'college': '理學院',
    'code': '2110',
    'name': '地理環境資源學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/40.pdf',
  },
  {
    'college': '理學院',
    'code': '2120',
    'name': '大氣科學系碩士班甲組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/41.pdf',
  },
  {
    'college': '理學院',
    'code': '2130',
    'name': '大氣科學系碩士班乙組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/42.pdf',
  },
  {
    'college': '理學院',
    'code': '2140',
    'name': '海洋研究所碩士班海洋物理組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/43.pdf',
  },
  {
    'college': '理學院',
    'code': '2150',
    'name': '海洋研究所碩士班海洋地質及地球物理組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/44.pdf',
  },
  {
    'college': '理學院',
    'code': '2160',
    'name': '海洋研究所碩士班海洋地質及地球物理組(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/45.pdf',
  },
  {
    'college': '理學院',
    'code': '2170',
    'name': '海洋研究所碩士班海洋化學組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/46.pdf',
  },
  {
    'college': '理學院',
    'code': '2180',
    'name': '海洋研究所碩士班海洋生物及漁業組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/47.pdf',
  },
  {
    'college': '理學院',
    'code': '2190',
    'name': '天文物理研究所碩士班(可選擇志願)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/48.pdf',
  },
  {
    'college': '理學院',
    'code': '2200',
    'name': '應用物理學研究所碩士班(可選擇志願)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/49.pdf',
  },
  {
    'college': '理學院',
    'code': '2210',
    'name': '應用數學科學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/50.pdf',
  },
  {
    'college': '理學院',
    'code': '2220',
    'name': '應用數學科學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/51.pdf',
  },
  {
    'college': '理學院',
    'code': '2230',
    'name': '氣候變遷與永續發展國際碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/52.pdf',
  },
  {
    'college': '理學院',
    'code': '2240',
    'name': '統計與數據科學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/53.pdf',
  },
  {
    'college': '社會科學院',
    'code': '3010',
    'name': '政治學系碩士班甲組(主修政治理論)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/54.pdf',
  },
  {
    'college': '社會科學院',
    'code': '3020',
    'name': '政治學系碩士班乙組(主修國際關係)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/55.pdf',
  },
  {
    'college': '社會科學院',
    'code': '3030',
    'name': '經濟學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/56.pdf',
  },
  {
    'college': '社會科學院',
    'code': '3040',
    'name': '社會學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/57.pdf',
  },
  {
    'college': '社會科學院',
    'code': '3050',
    'name': '社會工作學系碩士班甲組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/58.pdf',
  },
  {
    'college': '社會科學院',
    'code': '3060',
    'name': '社會工作學系碩士班乙組(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/59.pdf',
  },
  {
    'college': '社會科學院',
    'code': '3070',
    'name': '國家發展研究所碩士班甲組(主修全球化與科技治理)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/60.pdf',
  },
  {
    'college': '社會科學院',
    'code': '3080',
    'name': '國家發展研究所碩士班乙組(主修中國大陸與東亞研究)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/61.pdf',
  },
  {
    'college': '社會科學院',
    'code': '3090',
    'name': '新聞研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/62.pdf',
  },
  {
    'college': '社會科學院',
    'code': '3100',
    'name': '公共事務研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/63.pdf',
  },
  {
    'college': '醫學院',
    'code': '4010',
    'name': '臨床牙醫學研究所碩士班甲組(主修口腔病理學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/64.pdf',
  },
  {
    'college': '醫學院',
    'code': '4020',
    'name': '臨床牙醫學研究所碩士班乙組(主修牙體復形及美容牙科學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/65.pdf',
  },
  {
    'college': '醫學院',
    'code': '4030',
    'name': '臨床牙醫學研究所碩士班丙組(主修牙髓病學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/66.pdf',
  },
  {
    'college': '醫學院',
    'code': '4040',
    'name': '臨床牙醫學研究所碩士班丁組(主修牙周病學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/67.pdf',
  },
  {
    'college': '醫學院',
    'code': '4050',
    'name': '臨床牙醫學研究所碩士班戊組(主修補綴學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/68.pdf',
  },
  {
    'college': '醫學院',
    'code': '4060',
    'name': '臨床牙醫學研究所碩士班己組(主修兒童牙科學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/69.pdf',
  },
  {
    'college': '醫學院',
    'code': '4070',
    'name': '臨床牙醫學研究所碩士班庚組(主修齒顎矯正學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/70.pdf',
  },
  {
    'college': '醫學院',
    'code': '4080',
    'name': '臨床牙醫學研究所碩士班辛組(主修口腔顎面外科學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/71.pdf',
  },
  {
    'college': '醫學院',
    'code': '4090',
    'name': '臨床牙醫學研究所碩士班壬組(主修智慧口腔醫療學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/72.pdf',
  },
  {
    'college': '醫學院',
    'code': '4100',
    'name': '藥學系碩士班甲組(主修新藥探索)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/73.pdf',
  },
  {
    'college': '醫學院',
    'code': '4110',
    'name': '藥學系碩士班乙組(主修製藥科技)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/74.pdf',
  },
  {
    'college': '醫學院',
    'code': '4120',
    'name': '藥學系碩士班丙組(主修醫藥生技)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/75.pdf',
  },
  {
    'college': '醫學院',
    'code': '4130',
    'name': '醫學檢驗暨生物技術學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/76.pdf',
  },
  {
    'college': '醫學院',
    'code': '4140',
    'name': '護理學系碩士班甲組(專科護理師組)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/77.pdf',
  },
  {
    'college': '醫學院',
    'code': '4150',
    'name': '護理學系碩士班乙組(臨床研究護理師組)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/78.pdf',
  },
  {
    'college': '醫學院',
    'code': '4160',
    'name': '護理學系碩士班丙組(內外科護理組)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/79.pdf',
  },
  {
    'college': '醫學院',
    'code': '4170',
    'name': '護理學系碩士班丁組(婦女健康暨母嬰護理組)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/80.pdf',
  },
  {
    'college': '醫學院',
    'code': '4180',
    'name': '護理學系碩士班戊組(兒童暨家庭護理組)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/81.pdf',
  },
  {
    'college': '醫學院',
    'code': '4190',
    'name': '護理學系碩士班己組(精神暨心理衛生護理組)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/82.pdf',
  },
  {
    'college': '醫學院',
    'code': '4200',
    'name': '護理學系碩士班庚組(社區護理組)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/83.pdf',
  },
  {
    'college': '醫學院',
    'code': '4210',
    'name': '物理治療學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/84.pdf',
  },
  {
    'college': '醫學院',
    'code': '4220',
    'name': '職能治療學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/85.pdf',
  },
  {
    'college': '醫學院',
    'code': '4230',
    'name': '生理學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/86.pdf',
  },
  {
    'college': '醫學院',
    'code': '4240',
    'name': '生物化學暨分子生物學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/87.pdf',
  },
  {
    'college': '醫學院',
    'code': '4250',
    'name': '藥理學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/88.pdf',
  },
  {
    'college': '醫學院',
    'code': '4260',
    'name': '病理學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/89.pdf',
  },
  {
    'college': '醫學院',
    'code': '4270',
    'name': '病理學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/90.pdf',
  },
  {
    'college': '醫學院',
    'code': '4280',
    'name': '微生物學研究所碩士班微生物及免疫學組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/91.pdf',
  },
  {
    'college': '醫學院',
    'code': '4290',
    'name': '微生物學研究所碩士班熱帶醫學暨寄生蟲學組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/92.pdf',
  },
  {
    'college': '醫學院',
    'code': '4300',
    'name': '解剖學暨細胞生物學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/93.pdf',
  },
  {
    'college': '醫學院',
    'code': '4310',
    'name': '解剖學暨細胞生物學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/94.pdf',
  },
  {
    'college': '醫學院',
    'code': '4320',
    'name': '毒理學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/95.pdf',
  },
  {
    'college': '醫學院',
    'code': '4330',
    'name': '分子醫學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/96.pdf',
  },
  {
    'college': '醫學院',
    'code': '4340',
    'name': '分子醫學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/97.pdf',
  },
  {
    'college': '醫學院',
    'code': '4350',
    'name': '免疫學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/98.pdf',
  },
  {
    'college': '醫學院',
    'code': '4360',
    'name': '免疫學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/99.pdf',
  },
  {
    'college': '醫學院',
    'code': '4370',
    'name': '口腔生物科學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/100.pdf',
  },
  {
    'college': '醫學院',
    'code': '4380',
    'name': '口腔生物科學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/101.pdf',
  },
  {
    'college': '醫學院',
    'code': '4390',
    'name': '臨床藥學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/102.pdf',
  },
  {
    'college': '醫學院',
    'code': '4400',
    'name': '臨床藥學研究所碩士班(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/103.pdf',
  },
  {
    'college': '醫學院',
    'code': '4410',
    'name': '法醫學研究所碩士班甲組(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/104.pdf',
  },
  {
    'college': '醫學院',
    'code': '4420',
    'name': '腦與心智科學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/105.pdf',
  },
  {
    'college': '醫學院',
    'code': '4430',
    'name': '基因體暨蛋白體醫學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/106.pdf',
  },
  {
    'college': '醫學院',
    'code': '4440',
    'name': '醫學教育暨生醫倫理研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/107.pdf',
  },
  {
    'college': '醫學院',
    'code': '4450',
    'name': '醫療器材與醫學影像研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/108.pdf',
  },
  {
    'college': '醫學院',
    'code': '4460',
    'name': '醫療器材與醫學影像研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/109.pdf',
  },
  {
    'college': '醫學院',
    'code': '4470',
    'name': '醫療器材與醫學影像研究所碩士班(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/110.pdf',
  },
  {
    'college': '醫學院',
    'code': '4480',
    'name': '國際三校農業生技與健康醫療碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/111.pdf',
  },
  {
    'college': '醫學院',
    'code': '4490',
    'name': '醫藥法規科學碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/112.pdf',
  },
  {
    'college': '工學院',
    'code': '5010',
    'name': '土木工程學系碩士班大地工程組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/113.pdf',
  },
  {
    'college': '工學院',
    'code': '5020',
    'name': '土木工程學系碩士班測量及空間資訊組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/114.pdf',
  },
  {
    'college': '工學院',
    'code': '5030',
    'name': '土木工程學系碩士班測量及空間資訊組(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/115.pdf',
  },
  {
    'college': '工學院',
    'code': '5040',
    'name': '土木工程學系碩士班結構工程組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/116.pdf',
  },
  {
    'college': '工學院',
    'code': '5050',
    'name': '土木工程學系碩士班水利工程組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/117.pdf',
  },
  {
    'college': '工學院',
    'code': '5060',
    'name': '土木工程學系碩士班水利工程組(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/118.pdf',
  },
  {
    'college': '工學院',
    'code': '5070',
    'name': '土木工程學系碩士班交通工程組(主修交通運輸、道路及機場工程）',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/119.pdf',
  },
  {
    'college': '工學院',
    'code': '5080',
    'name': '土木工程學系碩士班交通工程組(主修交通運輸、道路及機場工程）(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/120.pdf',
  },
  {
    'college': '工學院',
    'code': '5090',
    'name': '土木工程學系碩士班電腦輔助工程組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/121.pdf',
  },
  {
    'college': '工學院',
    'code': '5100',
    'name': '土木工程學系碩士班電腦輔助工程組(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/122.pdf',
  },
  {
    'college': '工學院',
    'code': '5110',
    'name': '土木工程學系碩士班營建工程與管理',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/123.pdf',
  },
  {
    'college': '工學院',
    'code': '5120',
    'name': '機械工程學系碩士班(可選擇志願)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/124.pdf',
  },
  {
    'college': '工學院',
    'code': '5130',
    'name': '機械工程學系碩士班流體力學組(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/125.pdf',
  },
  {
    'college': '工學院',
    'code': '5140',
    'name': '化學工程學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/126.pdf',
  },
  {
    'college': '工學院',
    'code': '5150',
    'name': '工程科學及海洋工程學系碩士班甲組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/127.pdf',
  },
  {
    'college': '工學院',
    'code': '5160',
    'name': '工程科學及海洋工程學系碩士班乙組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/128.pdf',
  },
  {
    'college': '工學院',
    'code': '5170',
    'name': '工程科學及海洋工程學系碩士班丙組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/129.pdf',
  },
  {
    'college': '工學院',
    'code': '5180',
    'name': '工程科學及海洋工程學系碩士班丁組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/130.pdf',
  },
  {
    'college': '工學院',
    'code': '5190',
    'name': '材料科學與工程學系碩士班甲組(主修金屬、製程、陶瓷能源材料)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/131.pdf',
  },
  {
    'college': '工學院',
    'code': '5200',
    'name': '材料科學與工程學系碩士班乙組(主修高分子及軟質材料)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/132.pdf',
  },
  {
    'college': '工學院',
    'code': '5210',
    'name': '材料科學與工程學系碩士班丙組(主修電子材料)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/133.pdf',
  },
  {
    'college': '工學院',
    'code': '5220',
    'name': '材料科學與工程學系國際應用材料工程碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/134.pdf',
  },
  {
    'college': '工學院',
    'code': '5230',
    'name': '環境工程學研究所碩士班(可選擇志願)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/135.pdf',
  },
  {
    'college': '工學院',
    'code': '5240',
    'name': '應用力學研究所碩士班甲組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/136.pdf',
  },
  {
    'college': '工學院',
    'code': '5250',
    'name': '應用力學研究所碩士班乙組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/137.pdf',
  },
  {
    'college': '工學院',
    'code': '5260',
    'name': '應用力學研究所碩士班丙組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/138.pdf',
  },
  {
    'college': '工學院',
    'code': '5270',
    'name': '建築與城鄉研究所碩士班空間規劃設計專業組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/139.pdf',
  },
  {
    'college': '工學院',
    'code': '5280',
    'name': '建築與城鄉研究所碩士班其它專業組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/140.pdf',
  },
  {
    'college': '工學院',
    'code': '5290',
    'name': '建築與城鄉研究所碩士班原住民組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/141.pdf',
  },
  {
    'college': '工學院',
    'code': '5300',
    'name': '建築與城鄉研究所碩士班新住民組(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/142.pdf',
  },
  {
    'college': '工學院',
    'code': '5310',
    'name': '工業工程學研究所碩士班甲組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/143.pdf',
  },
  {
    'college': '工學院',
    'code': '5320',
    'name': '工業工程學研究所碩士班乙組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/144.pdf',
  },
  {
    'college': '工學院',
    'code': '5330',
    'name': '工業工程學研究所碩士班丙組(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/145.pdf',
  },
  {
    'college': '工學院',
    'code': '5340',
    'name': '醫學工程學系碩士班甲組(主修材料)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/146.pdf',
  },
  {
    'college': '工學院',
    'code': '5350',
    'name': '醫學工程學系碩士班乙組(主修力學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/147.pdf',
  },
  {
    'college': '工學院',
    'code': '5360',
    'name': '醫學工程學系碩士班乙組(主修力學)(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/148.pdf',
  },
  {
    'college': '工學院',
    'code': '5370',
    'name': '醫學工程學系碩士班丙組(主修電機、電子、資訊)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/149.pdf',
  },
  {
    'college': '工學院',
    'code': '5380',
    'name': '醫學工程學系碩士班丁組(主修生物、醫、農)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/150.pdf',
  },
  {
    'college': '工學院',
    'code': '5390',
    'name': '高分子科學與工程學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/151.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6010',
    'name': '農藝學系碩士班作物科學甲組(主修生理、生物技術、生產管理)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/152.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6020',
    'name': '農藝學系碩士班作物科學甲組(主修生理、生物技術、生產管理)(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/153.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6030',
    'name': '農藝學系碩士班作物科學乙組(主修遺傳、分子育種)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/154.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6040',
    'name': '農藝學系碩士班生物統計學組(主修生物統計、生物資訊)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/155.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6050',
    'name': '生物環境系統工程學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/156.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6060',
    'name': '農業化學系碩士班甲組(主修土壤環境與植物營養學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/157.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6070',
    'name': '農業化學系碩士班乙組(主修微生物學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/158.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6080',
    'name': '農業化學系碩士班丙組(主修食品化學與加工)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/159.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6090',
    'name': '森林環境暨資源學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/160.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6100',
    'name': '森林環境暨資源學系碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/161.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6110',
    'name': '森林環境暨資源學系碩士班(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/162.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6120',
    'name': '動物科學技術學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/163.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6130',
    'name': '動物科學技術學系碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/164.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6140',
    'name': '農業經濟學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/165.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6150',
    'name': '農業經濟學系碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/166.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6160',
    'name': '園藝暨景觀學系碩士班園藝作物組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/167.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6170',
    'name': '園藝暨景觀學系碩士班園產品處理及利用組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/168.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6180',
    'name': '園藝暨景觀學系碩士班景觀暨休憩組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/169.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6190',
    'name': '獸醫學系碩士班甲組(主修獸醫公共衛生及預防醫學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/170.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6200',
    'name': '獸醫學系碩士班乙組(主修基礎動物醫學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/171.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6210',
    'name': '生物產業傳播暨發展學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/172.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6220',
    'name': '生物產業傳播暨發展學系碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/173.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6230',
    'name': '生物機電工程學系碩士班機電控制、人工智慧組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/174.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6240',
    'name': '生物機電工程學系碩士班機械系統組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/175.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6250',
    'name': '生物機電工程學系碩士班生物程序組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/176.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6260',
    'name': '昆蟲學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/177.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6270',
    'name': '植物病理與微生物學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/178.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6280',
    'name': '食品科技研究所碩士班甲組(主修食品化學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/179.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6290',
    'name': '食品科技研究所碩士班乙組(主修食品微生物)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/180.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6300',
    'name': '食品科技研究所碩士班丙組(主修食品加工)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/181.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6310',
    'name': '食品科技研究所碩士班丁組(主修保健營養)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/182.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6320',
    'name': '食品科技研究所碩士班戊組(主修食品工程)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/183.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6330',
    'name': '生物科技研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/184.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6340',
    'name': '臨床動物醫學研究所碩士班甲組(伴侶動物組)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/185.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6350',
    'name': '臨床動物醫學研究所碩士班乙組(大動物及野生動物組)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/186.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6360',
    'name': '植物醫學碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/187.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6370',
    'name': '植物醫學碩士學位學程(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/188.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6380',
    'name': '植物醫學碩士學位學程(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/189.pdf',
  },
  {
    'college': '生物資源暨農學院',
    'code': '6390',
    'name': '分子暨比較病理生物學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/190.pdf',
  },
  {
    'college': '管理學院',
    'code': '7010',
    'name': '商學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/191.pdf',
  },
  {
    'college': '管理學院',
    'code': '7020',
    'name': '會計學系碩士班甲組(主修會計)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/192.pdf',
  },
  {
    'college': '管理學院',
    'code': '7030',
    'name': '會計學系碩士班乙組(主修商業智慧與資料分析)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/193.pdf',
  },
  {
    'college': '管理學院',
    'code': '7040',
    'name': '財務金融學系碩士班甲組(主修財務金融)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/194.pdf',
  },
  {
    'college': '管理學院',
    'code': '7050',
    'name': '財務金融學系碩士班乙組(主修財務工程)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/195.pdf',
  },
  {
    'college': '管理學院',
    'code': '7060',
    'name': '財務金融學系碩士班丙組(主修風險管理與保險)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/196.pdf',
  },
  {
    'college': '管理學院',
    'code': '7070',
    'name': '國際企業學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/197.pdf',
  },
  {
    'college': '管理學院',
    'code': '7080',
    'name': '國際企業學系碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/198.pdf',
  },
  {
    'college': '管理學院',
    'code': '7090',
    'name': '資訊管理學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/199.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8010',
    'name': '健康政策與管理研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/200.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8020',
    'name': '健康政策與管理研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/201.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8030',
    'name': '健康行為與社區科學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/202.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8040',
    'name': '健康行為與社區科學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/203.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8050',
    'name': '環境與職業健康科學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/204.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8060',
    'name': '流行病學與預防醫學研究所碩士班甲組(主修流行病學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/205.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8070',
    'name': '流行病學與預防醫學研究所碩士班乙組(主修預防醫學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/206.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8080',
    'name': '健康數據拓析統計研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/207.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8090',
    'name': '公共衛生碩士學位學程(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/208.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8100',
    'name': '食品安全與健康研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/209.pdf',
  },
  {
    'college': '公共衛生學院',
    'code': '8110',
    'name': '全球衛生碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/210.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9010',
    'name': '電機工程學系碩士班甲組(主修自動控制)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/211.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9020',
    'name': '電機工程學系碩士班乙組(主修電力系統與電力電子)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/212.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9030',
    'name': '電機工程學系碩士班丙組(主修計算機科學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/213.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9040',
    'name': '電機工程學系資訊安全碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/214.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9050',
    'name': '資訊工程學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/215.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9060',
    'name': '資訊工程學系人工智慧碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/216.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9070',
    'name': '光電工程學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/217.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9080',
    'name': '電信工程學研究所碩士班甲組(主修電波)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/218.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9090',
    'name': '電信工程學研究所碩士班乙組(主修通訊與信號處理)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/219.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9100',
    'name': '電信工程學研究所碩士班丙組(主修資料科學與智慧網路)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/220.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9110',
    'name': '電子工程學研究所碩士班甲組(主修數位積體電路與系統)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/221.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9120',
    'name': '電子工程學研究所碩士班甲組(主修數位積體電路與系統)(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/222.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9130',
    'name': '電子工程學研究所碩士班乙組(主修類比積體電路與系統)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/223.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9140',
    'name': '電子工程學研究所碩士班丙組(主修電子設計自動化)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/224.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9150',
    'name': '電子工程學研究所碩士班丙組(主修電子設計自動化)(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/225.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9160',
    'name': '電子工程學研究所碩士班丁組(主修奈米電子含光電半導體)(可選擇志願)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/226.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9170',
    'name': '電子工程學研究所碩士班丁組(主修奈米電子含光電半導體)(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/227.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9180',
    'name': '資訊網路與多媒體研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/228.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9190',
    'name': '生醫電子與資訊學研究所碩士班甲組(主修生醫電子一)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/229.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9200',
    'name': '生醫電子與資訊學研究所碩士班乙組(主修生醫電子二)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/230.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9210',
    'name': '生醫電子與資訊學研究所碩士班丙組(主修生醫資訊)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/231.pdf',
  },
  {
    'college': '電機資訊學院',
    'code': '9220',
    'name': '資料科學碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/232.pdf',
  },
  {
    'college': '法律學院',
    'code': 'A010',
    'name': '法律學系碩士班甲組(主修基礎法學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/233.pdf',
  },
  {
    'college': '法律學院',
    'code': 'A020',
    'name': '法律學系碩士班乙組(主修公法學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/234.pdf',
  },
  {
    'college': '法律學院',
    'code': 'A030',
    'name': '法律學系碩士班丙組(主修民事法學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/235.pdf',
  },
  {
    'college': '法律學院',
    'code': 'A040',
    'name': '法律學系碩士班丁組(主修刑事法學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/236.pdf',
  },
  {
    'college': '法律學院',
    'code': 'A050',
    'name': '法律學系碩士班戊組(主修財稅法學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/237.pdf',
  },
  {
    'college': '法律學院',
    'code': 'A060',
    'name': '法律學系碩士班己組(主修經濟法學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/238.pdf',
  },
  {
    'college': '法律學院',
    'code': 'A070',
    'name': '法律學系碩士班庚組(主修國際法學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/239.pdf',
  },
  {
    'college': '法律學院',
    'code': 'A080',
    'name': '法律學系碩士班辛組(主修商事法學)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/240.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B010',
    'name': '生命科學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/241.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B020',
    'name': '生命科學系碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/242.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B030',
    'name': '植物科學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/243.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B040',
    'name': '植物科學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/244.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B050',
    'name': '分子與細胞生物學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/245.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B060',
    'name': '生態學與演化生物學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/246.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B070',
    'name': '生態學與演化生物學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/247.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B080',
    'name': '漁業科學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/248.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B090',
    'name': '生化科學研究所碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/249.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B100',
    'name': '生化科學研究所碩士班(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/250.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B110',
    'name': '生化科技學系碩士班',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/251.pdf',
  },
  {
    'college': '生命科學院',
    'code': 'B120',
    'name': '基因體與系統生物學碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/252.pdf',
  },
  {
    'college': '國際政經學院',
    'code': 'C010',
    'name': '政治經濟碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/253.pdf',
  },
  {
    'college': '國際政經學院',
    'code': 'C020',
    'name': '財金碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/254.pdf',
  },
  {
    'college': '國際政經學院',
    'code': 'C030',
    'name': '領導與管理碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/255.pdf',
  },
  {
    'college': '共同教育中心',
    'code': 'H010',
    'name': '統計碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/256.pdf',
  },
  {
    'college': '共同教育中心',
    'code': 'H020',
    'name': '統計碩士學位學程(新住民生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/257.pdf',
  },
  {
    'college': '共同教育中心',
    'code': 'H030',
    'name': '運動設施與健康管理碩士學位學程運動管理組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/258.pdf',
  },
  {
    'college': '共同教育中心',
    'code': 'H040',
    'name': '運動設施與健康管理碩士學位學程運動管理組(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/259.pdf',
  },
  {
    'college': '共同教育中心',
    'code': 'H050',
    'name': '運動設施與健康管理碩士學位學程健康管理組',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/260.pdf',
  },
  {
    'college': '共同教育中心',
    'code': 'H060',
    'name': '運動設施與健康管理碩士學位學程健康管理組(在職生)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/261.pdf',
  },
  {
    'college': '共同教育中心',
    'code': 'H070',
    'name': '全球農業科技與基因體科學碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/262.pdf',
  },
  {
    'college': '共同教育中心',
    'code': 'H080',
    'name': '生物多樣性國際碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/263.pdf',
  },
  {
    'college': '共同教育中心',
    'code': 'H090',
    'name': '智慧醫療與健康資訊碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/264.pdf',
  },
  {
    'college': '共同教育中心',
    'code': 'H100',
    'name': '防災減害與韌性碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/265.pdf',
  },
  {
    'college': '重點科技研究學院',
    'code': 'K010',
    'name': '積體電路設計與自動化碩士學位學程甲組(主修數位積體電路與系統)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/266.pdf',
  },
  {
    'college': '重點科技研究學院',
    'code': 'K020',
    'name': '積體電路設計與自動化碩士學位學程乙組(主修類比積體電路與系統)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/267.pdf',
  },
  {
    'college': '重點科技研究學院',
    'code': 'K030',
    'name': '積體電路設計與自動化碩士學位學程丙組(主修電子設計自動化)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/268.pdf',
  },
  {
    'college': '重點科技研究學院',
    'code': 'K040',
    'name': '元件材料與異質整合碩士學位學程甲組(主修奈米電子含光電半導體)(可選擇志願)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/269.pdf',
  },
  {
    'college': '重點科技研究學院',
    'code': 'K050',
    'name': '元件材料與異質整合碩士學位學程乙組(主修材料與異質整合)',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/270.pdf',
  },
  {
    'college': '重點科技研究學院',
    'code': 'K060',
    'name': '奈米工程與科學碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/271.pdf',
  },
  {
    'college': '重點科技研究學院',
    'code': 'K070',
    'name': '精準健康碩士學位學程',
    'href': 'https://exam.aca.ntu.edu.tw/graf/brochure/115/272.pdf',
  },
];

export const BASE_TITLE = '臺灣大學 115 學年度碩士甄試招生簡章查詢網【網友自製】';
